name: atomic
description: custom-fedora-image
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: 43

modules:
  - type: files
    files:
      - source: etc
        destination: /etc
  
  - type: dnf
    install:
      packages:
        - terra-release
        - noctalia-shell
        - niri
        - xorg-x11-server-Xwayland
        - wl-clipboard
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring
        - stow
        - neovim
        - git
        - just
      exclude:
        - waybar
        - fuzzel
