name: atomic
description: custom-fedora-image
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: 43

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Dotfiles Manager
  - type: chezmoi
    repository: https://github.com/zygi-bomba/dotfiles.git
    branch: main
    file-conflict-policy: replace
 
  - type: dnf
    repos:
      files:
        - https://raw.githubusercontent.com/terrapkg/subatomic-repos/main/terra.repo
      copr:
        - atim/nushell 
        - yalter/niri 
    install:
      packages:
        # Window Manager & Compositor
        - noctalia-shell
        - niri
        
        # Wayland/X11 Support
        - xorg-x11-server-Xwayland
        - wl-clipboard
        - cliphist
        
        # Desktop Portal
        - xdg-desktop-portal-wlr

        # Containers
        - distrobox
        - podman

        # Terminal, shell
        - ghostty
        - nushell

        # VPN
        - NetworkManager-openconnect
        - vpnc-script
        - wireguard-tools
        
        # Terra Repository
        - terra-release
        
        # Secret management
        - vault

        - gcc
    remove:
      packages:
        - tmux
        - waybar
        - fuzzel

  - type: default-flatpaks
    configurations:
      - scope: user
        notify: false
        repo:
          title: Flathub (user)
        install:
          - app.zen_browser.zen
          - md.obsidian.Obsidian
          - com.github.zocker_160.SyncThingy
          - org.virt_manager.virt-manager
          - org.virt_manager.virt_manager.Extension.Qemu
        
      - scope: system
        notify: false
        repo:
          title: Flathub (system)
        install:
          - com.github.tchx84.Flatseal

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - Inter
    
  - type: systemd
    system:
      enabled:
        - set-user-shell.service
        - set-user-shell-on-update.path
        - vpn-vault.service
    
  - type: signing
  
  - type: script
    snippets:
      - "chmod 0600 /etc/NetworkManager/system-connections/*.nmconnection"
      - "chmod +x /usr/bin/vpn-up.sh"
