name: atomic
description: custom-fedora-image
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: 43

modules:
  - type: files
    files:
      - source: etc
        destination: /etc
  
  - type: dnf
    repos:
      files:
        - https://raw.githubusercontent.com/terrapkg/subatomic-repos/main/terra.repo
      copr:
        - yalter/niri 
    install:
      packages:
        # Window Manager & Compositor
        - noctalia-shell
        - niri
        
        # Wayland/X11 Support
        - xorg-x11-server-Xwayland
        - wl-clipboard
        
        # Desktop Portals & Keyring
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring
        
        # Development Tools
        - neovim
        - lazygit
        - fd-find
        - curl
        - ripgrep
        - tree-sitter-cli
        - stow
        - git
        - just
        
        # Terra Repository
        - terra-release
      exclude:
        - waybar
        - fuzzel

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install:
          - app.zen_browser.zen
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
