name: atomic
description: Moja reprodukowalna Fedora
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: 43

modules:
  - type: files
    files:
      - source: etc
        destination: /etc
  
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
    install:
      - terra-release
      - noctalia-shell
      - niri
      - xorg-x11-server-Xwayland
      - wl-clipboard
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-gnome
      - gnome-keyring
      - stow
      - neovim
      - git
      - just
  
  - type: script
    scripts:
      - custom-setup.sh
