name: atomic
description: Moja reprodukowalna Fedora
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: 43

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/yusdacra/niri/repo/fedora-%OS_VERSION%/yusdacra-niri.repo
    install:
      - niri
      - noctalia
      - foot         # Terminal
      - waybar       # Pasek zadań
      - swaybg       # Tapeta
      - fuzzel       # Menu aplikacji (Wayland-native)
      - xorg-x11-server-Xwayland

  - type: files # Kopiuje pliki z folderu config/files do obrazu
  
  - type: script
    scripts:
      - custom-setup.sh
