name: atomic
description: custom-fedora-image
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: 43

modules:
  - type: files
    files:
      - source: etc
        destination: /etc
  
  - type: dnf
    install:
      packages:
        - terra-release
        - noctalia-shell
        - niri
  
        - xorg-x11-server-Xwayland
        - wl-clipboard
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring
  
        # LazyVim
        - neovim
        - lazygit 
        - fd-find 
        - curl
        - ripgrep
        - tree-sitter-cli
  
        - stow
        - git
        - just
      exclude:
        - waybar
        - fuzzel

  - type: default-flatpaks
      configurations:
        - notify: true
          scope: system
          # If no repo information is specified, Flathub will be used by default
          install:
            - app.zen_browser.zen
        - scope: user # Also add Flathub user repo, but no user packages
  
    - type: signing # this sets up the proper policy & signing files for signed images to work fully
