name: atomic
description: Moja reprodukowalna Fedora
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: 43

modules:
  - type: files
    files:
      - etc: /etc # To kopiuje config/files/etc do systemowego /etc
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
    install:
      - terra-release # To zainstaluje klucze GPG i konfigurację na stałe
      - noctalia-shell
      - niri
      - foot         # Terminal
      - waybar       # Pasek zadań
      - swaybg       # Tapeta
      - fuzzel       # Menu aplikacji (Wayland-native)
      - xorg-x11-server-Xwayland
  
  - type: script
    scripts:
      - custom-setup.sh
