name: atomic
description: custom-fedora-image
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: 43

modules:
  - type: files
    files:
      - source: etc
        destination: /etc

  - type: chezmoi
    repository: https://github.com/zygi-bomba/dotfiles.git
    branch: main
    file-conflict-policy: replace
  
  - type: dnf
    repos:
      files:
        - https://raw.githubusercontent.com/terrapkg/subatomic-repos/main/terra.repo
      copr:
        - atim/nushell 
        - yalter/niri 
    install:
      packages:
        # Window Manager & Compositor
        - noctalia-shell
        - niri
        
        # Wayland/X11 Support
        - xorg-x11-server-Xwayland
        - wl-clipboard
        - cliphist
        
        # Desktop Portals & Keyring
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring
        
        - distrobox
        - podman
        
        - ghostty
        - nushell
        
        # Terra Repository
        - terra-release    
    remove:
      packages:
        - tmux
        - waybar
        - fuzzel

  - type: default-flatpaks
    configurations:
      - scope: user
        notify: false
        repo:
          # you can override the title to make inclusion of both system and user repos clearer
          title: Flathub (user)
        install:
          - app.zen_browser.zen
        
      - scope: system
        notify: false
        repo:
          title: Flathub (system)
        install:
          - com.github.tchx84.Flatseal

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - Inter
    
  - type: systemd
    system:
      enabled:
        - set-user-shell.service
        - set-user-shell-on-update.path
    
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
