name: atomic
description: custom-fedora-image
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: 43

modules:
  - type: files
    files:
      - source: etc
        destination: /etc
  
  - type: chezmoi
    repository: https://github.com/zygi-bomba/dotfiles.git
    branch: main
    file-conflict-policy: replace
  
  - type: dnf
    repos:
      files:
        - https://raw.githubusercontent.com/terrapkg/subatomic-repos/main/terra.repo
      copr:
        - yalter/niri 
    install:
      packages:
        # Window Manager & Compositor
        - noctalia-shell
        - niri
        
        # Wayland/X11 Support
        - xorg-x11-server-Xwayland
        - wl-clipboard
        
        # Desktop Portals & Keyring
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring
        
        - distrobox
        - podman

        - ghostty
        
        # Terra Repository
        - terra-release
      exclude:
        - waybar
        - fuzzel

  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          # you can override the title to make inclusion of both system and user repos clearer
          title: Flathub (user)
      - scope: system
        repo:
          title: Flathub (system)
        install: # system flatpaks we want all users to have and not remove
          - com.github.tchx84.Flatseal
          - app.zen_browser.zen
    
  - type: script
    scripts:
      - install-packages.sh

  - type: containerfile
    snippets:
      - RUN --mount=type=tmpfs,target=/tmp curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
    
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
